### ISSUE TITLE
Implement a `clientId` cookie.

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-authn-token-http#6]
Yes, there should be an issue to implement an actual cookie for that.

_Originally posted by @dlongley in https://github.com/digitalbazaar/bedrock-authn-token-http/pull/5_

**Comment by mattcollier** [comment]
This pertains to this FIXME: https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L160

This implies that we need to also update the client code to transact with cookies.

@dlongley what's the priority on this?

**Comment by dlongley** [comment]
@mattcollier, this is in P1 territory, we can't use this module in production without it.

**Comment by mattcollier** [comment]
Details:

- Add option to bedrock-authn-token stack to allow long (for links) or short (for humans to type) nonces, perhaps the name for the `style`/`entryStyle`/`inputStyle` of nonce should be `human`/`manual` or `link`/`machine` or something. The human version would ideally be a 6 digit number, the link would be too long to enter manually to discourage phishing scams to trick people into entering them vs. following the link. We need to ensure our security architecture prevents attackers from abusing the short 6 digit codes; perhaps token client registration as a prereq for entering those codes is sufficient to do that (likely, but not fully researched/explored/reasoned through).
- When an authn nonce token has already been created we can't resend one (need to add code to delete the old one first/make sure we do this safely so an attacker can't prevent a user from logging in)
- Replace FIXME clientId for device registration to a cookie value
Mostly a bikeshedding exercise: we need a new cookie, it needs a name, we need settings/config for that cookie, etc., need to hook that cookie up and replace the FIXMEs

**Comment by JSAssassin** [comment]
@dlongley can you give me some more information about the cookie implementation? What would be its settings/config?

**Comment by dlongley** [comment]
@JSAssassin, the cookie should be very similar to the session cookie we have (copy its settings). It should be http-only (unless we discover that's a problem for some reason). If we can name it something short, all the better, like `cid` for "client ID" (if not already taken or something). Its value should just be a random value -- we can probably use bnid to generate a 128-bit random ID. We should allow for its max age to be configurable via `config.js` and default it to say 30 days. Let me know if that covers what you need to know.

@davidlehn any opinions on the default max age for the client ID cookie that represents when the user last "registered their device"? Once the client ID cookie expires, it would mean that whenever their session expires and they want to log in again, they will have to do device registration again. But so long as their session was around, they wouldn't. (At least, this is my expectation of the behavior).
